name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  alejandra:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: alejandra check
        run: nix develop -c alejandra --check .

  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Setup bun Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: bun install
        run: nix develop -c bun install
      - name: lint
        run: nix develop -c bun lint